#! /bin/sh

# This script creates diff-based Postgres dumps.  On Sunday, a full dump
# of each database is made.  On other days, a full dump is made, diffed
# against the last (uncompressed) dump, and only the diff is stored.
#

LANG=C
HOME=/root
PGUSER=postgres
export LANG HOME PGUSER

DIR="/var/backups/pgsql"
OPTS="-Fp -bcOx --if-exists"
skip='^template0$'

psql -c 'SELECT 1' template1 >/dev/null 2>&1 || exit 0

set -e

for db in $(psql -Atc 'SELECT datname FROM pg_database' template1 | egrep -v -- "${skip}" ); do
	DDIR="${DIR}/${db}"
	mkdir -p "${DDIR}"
	cd "${DDIR}"

	echo "==> ${db}"

	# Only keep the 2 most recent full backups, and the 16 most
	# recent diffs.
	( ls -1rt *.sql.gz | head -n -2 | xargs rm ) >/dev/null 2>&1 || true
	( ls -1rt *.xdelta | head -n -16 | xargs rm ) >/dev/null 2>&1 || true

	lastfull=$(ls -1tr | grep "${db}\.full\.....-..-..\.sql\.gz" | tail -1)

	if [ -z "${lastfull}" -o $(date +%a) = Sun ]; then
		fname="$(date +"${db}.full.%Y-%m-%d.sql.gz")"
		pg_dump  ${OPTS} "${db}" | gzip > ".${fname}"
		mv ".${fname}" "${fname}"
	else
		fname="$(date +"${db}.incr.%Y-%m-%d.sql")"
		pg_dump ${OPTS} "${db}" > "${fname}"

		xdelta3 -9 -I 0 -S djw -B 134217728 -W 16777216 -P 524288 -e -f -s "${lastfull}" "${fname}" "${fname}.xdelta"
		rm -f "${fname}"
	fi
done

{% if dump_pgsql_healthcheck_token %}
    curl -fsS --retry 3 https://hchk.io/{{ dump_pgsql_healthcheck_token }}
{% endif %}
