# default variables for nginx role
---

nginx_dir: /etc/nginx

nginx_log_dir: /var/log/nginx

# global log files
nginx_error_log: "{{ nginx_log_dir }}/error.log"
nginx_access_log: "{{ nginx_log_dir }}/access.log"

# site specific log files
nginx_app_error_log: "{{ nginx_app_log_dir }}/app_error.log"
nginx_app_access_log: "{{ nginx_app_log_dir }}/app_access.log"

dhe_param_path: /etc/ssl/certs/dhparam.pem

nginx_confd_dir: "{{nginx_dir}}/conf.d"

nginx_shared_confs:
  - {file: ssl_params, directory: "{{ nginx_dir }}", filename: ssl_params}
  - {file: gzip_params, directory: "{{ nginx_dir }}", filename: gzip_params}

nginx_site_confs:
  - {
      file: "site.conf",
      directory: "{{ nginx_confd_dir }}",
      filename: "{{ fqdn }}.conf"
  }

nginx_app_error_log: "/var/log/nginx/{{ deployment_slug }}_error.log"
nginx_app_access_log: "/var/log/nginx/{{ deployment_slug }}_access.log"
