# configures SFTP only users limiting them to SFTP access only.
---

- name: ensure sftp only group exists
  group: name=sftponly state=present
  become: true

- name: ensure users are synced
  user:
    name: "{{ item.name }}"
    force: yes
    remove: yes
    password: "{{ item.shadow_pass | default(omit) }}"
    state: "{{ item.state | default(omit) }}"
    shell: "{{ item.shell | default('/bin/bash') }}"
    groups: "{{ item.groups | default('sudo') }}"
  with_items: "{{ sftp_users }}"
  become: true

- name: ensure user public keys are synced
  authorized_key:
    user: "{{ item.name }}"
    key: "{{ item.public_keys | join('\n') }}"
    state: present
    exclusive: yes
  with_items: "{{ sftp_users }}"
  when: item.public_keys is defined and item.public_keys | length > 0
  become: true

- name: ensure root owns home directory for chroot
  file:
    path: /home/{{ item.name }}/
    state: directory
    owner: root
    group: root
  with_items: "{{ sftp_users }}"
  become: true

- name: ensure files dir exists
  file:
    path: /home/{{ item.name }}/files
    state: directory
    owner: "{{ item.name }}"
    group: "{{ item.name }}"
  with_items: "{{ sftp_users }}"
  become: true

- name: ensure internal-sftp used as sftp subsystem
  lineinfile:
    dest: /etc/ssh/sshd_config
    state: present
    regexp: "^Subsystem sftp"
    line: "Subsystem sftp internal-sftp"
  notify: restart ssh

- name: ensure sftp jailing in ssh
  blockinfile:
    dest: /etc/ssh/sshd_config
    block: |
      Match Group sftponly
        AuthorizedKeysFile /home/%u/.ssh/authorized_keys
        ChrootDirectory /home/%u/
        ForceCommand internal-sftp
        AllowTcpForwarding no
        PermitTunnel no
        X11Forwarding no
  notify: restart ssh
