# Handles the set-up of Django
---
- name: run production configuration
  include: production.yml
  when: env == 'production'

- name: install system package dependencies
  apt:
    name: "{{ item }}"
    state: latest
    update_cache: yes
    cache_valid_time: "{{ apt_cache_valid_time }}"
  with_items: "{{ django_apt_dependencies }}"
  become: yes

- name: install requirements
  pip:
    requirements: "{{ base_dir }}/requirements/{{ env }}.txt"
    virtualenv: "{{ virtualenv_path }}"
  become: true
  become_user: "{{ deployment_user }}"

- name: django migrate
  django_manage:
    command: migrate
    settings: "{{ django_settings_module }}"
    virtualenv: "{{ virtualenv_path }}"
    app_path: "{{ django_dir }}"
  become: true
  become_user: "{{ deployment_user }}"

- name: install frontend asset pipeline
  npm: path={{ base_dir }}
  become: yes
  become_user: "{{ deployment_user }}"

- name: npm run production
  shell: npm run production
  args:
    chdir: "{{ base_dir }}"
  become: true
  become_user: "{{ deployment_user }}"
  when: not is_vagrant

- name: django collectstatic
  django_manage:
    command: collectstatic
    settings: "{{ django_settings_module }}"
    virtualenv: "{{ virtualenv_path }}"
    app_path: "{{ django_dir }}"
  become: true
  become_user: "{{ deployment_user }}"
