# Handles production specific django configuration
---

- name: ensure django log directory exists
  file:
    path: "{{ django_log_dir }}"
    owner: "root"
    group: "deployment"
    mode: "u=rwx,g=rwx,o=rx"
    state: directory
  become: true

- name: ensure application log directory exists
  file:
    path: "{{ project_log_dir }}"
    owner: "{{ deployment_user }}"
    group: "{{ deployment_user }}"
    state: directory
  become: true

- name: ensure application log file exists
  file:
    path: "{{ project_log_file }}"
    owner: "{{ deployment_user }}"
    group: "{{ deployment_user }}"
    state: touch
  become: true

- name: ensure django projects dir exists
  file:
    path: "{{ django_projects_dir }}"
    state: directory
  become: true

- name: ensure project base directory exists
  file:
    path: "{{ base_dir }}"
    state: directory
    owner: "{{ deployment_user }}"
    group: "{{ deployment_user }}"
  become: true

- name: ensure virtualenvs directory exists
  file:
    path: "{{ virtualenv_root }}"
    state: directory
  become: true

- name: ensure project virtualenv directory exists
  file:
    path: "{{ virtualenv_path }}"
    state: directory
    owner: "{{ deployment_user }}"
    group: "{{ deployment_user }}"
  become: true

- name: pull project from repository
  git:
    repo: "{{ git_uri }}"
    dest: "{{ base_dir }}"
    version: "{{ git_version }}"
    update: no
  become: true
  become_user: "{{ deployment_user }}"
