---
# Handlers for Postfix notifications.

- name: stop postfix
  service:
    name: "{{ postfix_service }}"
    state: stopped
  become: yes

- name: start postfix
  service:
    name: "{{ postfix_service }}"
    state: started
    enabled: yes
  become: yes

- name: restart postfix
  service:
    name: "{{ postfix_service }}"
    state: restarted
    enabled: yes
  become: yes

- name: postmap sasl
  command: /usr/sbin/postmap {{ postfix_config_dir }}/sasl_passwd
  become: yes
