# Defines variables for the base role
---

base_apt_packages:
  - build-essential
  - anacron
  - unattended-upgrades
  - bash-completion
  - ntp
  - vim
  - git
  - python
  - python-dev
  - python-pip

base_python_packages:
  - virtualenv
  - glances
