# Generate strong dhe param and ensure SSL certificates are present
---

- name: generate strong dhe parameter
  shell: openssl dhparam -dsaparam -out {{ dhe_param_path }} 4096
  args:
    creates: "{{ dhe_param_path }}"
  notify: restart nginx
  become: yes
