# Playbook for provisioning local development machines using vagrant
---

- hosts: development
  become_method: sudo
  vars_files:
    - vars/development.yml
  roles:
    - {role: base}
    - {role: users}
    - {role: ANXS.postgresql, become: yes}
    - {role: geerlingguy.redis, become: yes}
    - {role: nodejs}
    - {role: elasticsearch, become: yes, when: wagtail}
    - {role: django}
