# Playbook for provisioning production machines
---

- hosts: production
  become_method: sudo
  roles:
    - {role: base}
    - {role: security}
    - {role: users}
    - {role: ANXS.postgresql, become: yes}
    - {role: geerlingguy.redis, become: yes}
    - {role: postfix}
    - {role: nodejs}
    - {role: uwsgi}
    - {role: thefinn93.letsencrypt, become: yes, when: ssl}
    - {role: nginx}
    - {role: geerlingguy.elasticsearch, become: yes, when: wagtail}
    - {role: django}
    - {role: backups, when: not is_vagrant}
