# Requirements file specifying the 3rd party roles required by the project
---

- src: ANXS.postgresql
  version: v1.5.0

- src: geerlingguy.redis
  version: 1.4.1

- src: thefinn93.letsencrypt

#- src: geerlingguy.elasticsearch
#  version: 2.1.2
