# Playbook for provisioning production machines
---

- hosts: production
  become_method: sudo
  roles:
    - {role: base}
    - {role: security}
    - {role: users}
    - {role: ANXS.postgresql, become: yes}
    - {role: geerlingguy.redis, become: yes}
    - {role: nodejs}
    - {role: uwsgi}
    - {role: nginx}
    - {role: django}
