# Defines variables for production hosts
---

#
# general

env: production

fqdn: example.com

#
# django
#

django_projects_dir: /usr/local/django
base_dir: "{{ django_projects_dir }}/{{ fqdn }}"
django_dir: "{{ base_dir }}/{{ project_name }}"

#
# users
#

deployment_user: "{{ project_name }}"

users:
  - name: "{{ deployment_user }}"
    state: present
    groups: deployment

#
# virtualenv
#

virtualenv_root: /home/vagrant/.virtualenvs
virtualenv_path: "{{ virtualenv_root }}/{{ project_name }}"
